layout_spectrum: 0.15834245434962213
typography_spectrum: 0.3182640033774078
color:
  brandStrength: 0.912254192866385
  lightness: 0.813266014913097
  saturation: 0.3817673104349524
  rhythmicContrast: 0.35011953953653574
  brandColors:
    - '#450003'
    - '#5C0002'
    - '#94090D'
    - '#D40D12'
    - '#FF1D23'
coverPrefs:
  filter: false
content_rating:
  adult: false
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/0f207ee1-af4d-4746-ae29-edd3c3c31527.jpg
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/47ecd191-4ef0-4120-a720-4d7b8531fc5b.png
name: Pappy Productions
navigation:
  - name: Photo Booth
    id: 9df5b283-2cd9-4776-a3d0-61839f9bf0d5
    type: content
  - name: Real Estate Photography
    id: abe61936-f922-4eba-9b8a-1e89099e5b0b
    type: content
  - name: Dj Pappy
    id: 0afd7a70-b6b3-493d-90eb-441056d5ce51
    type: content
title: Pappy Productions
description: Media Services
purpose:
  - type: contact
    url: 'mailto:bennyhipp@gmail.com'
    label: Contact me
